"""Composition-test cases (data), generated from the retired test.yaml."""

CASES = [{'name': 'basic',
  'spec': {'compositionPath': 'apis/ctp/composition.yaml',
           'xrdPath': 'apis/ctp/definition.yaml',
           'validate': True,
           'timeoutSeconds': 60,
           'xr': {'apiVersion': 'gcp.platform.upbound.io/v1alpha1',
                  'kind': 'ControlPlane',
                  'metadata': {'name': 'test-cp'},
                  'spec': {'parameters': {'id': 'test-cp',
                                          'location': 'us-central1',
                                          'project': 'my-project',
                                          'version': '1.34',
                                          'nodes': {'count': 2,
                                                    'machineType': 'e2-standard-2'}}}},
           'assertResources': [{'apiVersion': 'gcp.platform.upbound.io/v1alpha1',
                                'kind': 'Network',
                                'metadata': {'name': 'test-cp'},
                                'spec': {'parameters': {'id': 'test-cp',
                                                        'region': 'us-central1',
                                                        'providerConfigName': 'default'}}},
                               {'apiVersion': 'gcp.platform.upbound.io/v1alpha1',
                                'kind': 'GKE',
                                'metadata': {'name': 'test-cp'},
                                'spec': {'parameters': {'id': 'test-cp',
                                                        'project': 'my-project',
                                                        'region': 'us-central1',
                                                        'version': '1.34',
                                                        'workloadIdentity': {'enabled': True},
                                                        'nodes': {'count': 2,
                                                                  'instanceType': 'e2-standard-2'}}}},
                               {'apiVersion': 'helm.m.crossplane.io/v1beta1',
                                'kind': 'Release',
                                'metadata': {'name': 'test-cp-uxp'},
                                'spec': {'forProvider': {'chart': {'version': '2.2.1-up.1'},
                                                         'values': {'upbound': {'manager': {'metering': {'podSecurityContext': {'fsGroup': 65532,
                                                                                                                                'fsGroupChangePolicy': 'OnRootMismatch'}}}}}}}},
                               {'apiVersion': 'helm.m.crossplane.io/v1beta1',
                                'kind': 'Release',
                                'metadata': {'name': 'test-cp-certmanager'},
                                'spec': {'forProvider': {'chart': {'name': 'cert-manager',
                                                                   'repository': 'https://charts.jetstack.io',
                                                                   'version': 'v1.20.3'},
                                                         'namespace': 'cert-manager'}}},
                               {'apiVersion': 'protection.crossplane.io/v1beta1',
                                'kind': 'Usage',
                                'metadata': {'name': 'test-cp-usage-release-gke'},
                                'spec': {'of': {'kind': 'GKE'},
                                         'by': {'kind': 'Release'}}},
                               {'apiVersion': 'protection.crossplane.io/v1beta1',
                                'kind': 'Usage',
                                'metadata': {'name': 'test-cp-usage-gke-network'},
                                'spec': {'of': {'kind': 'Network'},
                                         'by': {'kind': 'GKE'}}}]}},
 {'name': 'backup-enabled',
  'spec': {'compositionPath': 'apis/ctp/composition.yaml',
           'xrdPath': 'apis/ctp/definition.yaml',
           'validate': True,
           'timeoutSeconds': 60,
           'xr': {'apiVersion': 'gcp.platform.upbound.io/v1alpha1',
                  'kind': 'ControlPlane',
                  'metadata': {'name': 'test-cp'},
                  'spec': {'parameters': {'id': 'test-cp',
                                          'location': 'us-central1',
                                          'project': 'my-project',
                                          'version': '1.34',
                                          'nodes': {'count': 2,
                                                    'machineType': 'e2-standard-2'},
                                          'backup': {'enabled': 'yes',
                                                     'location': 'mybackup001'}}}},
           'assertResources': [{'apiVersion': 'storage.gcp.m.upbound.io/v1beta1',
                                'kind': 'Bucket',
                                'metadata': {'name': 'mybackup001'},
                                'spec': {'forProvider': {'location': 'us-central1'}}},
                               {'apiVersion': 'kubernetes.m.crossplane.io/v1alpha1',
                                'kind': 'Object',
                                'metadata': {'name': 'test-cp-backup-config'},
                                'spec': {'forProvider': {'manifest': {'spec': {'objectStorage': {'provider': 'GCP',
                                                                                                 'bucket': 'mybackup001',
                                                                                                 'credentials': {'source': 'InjectedIdentity'}}}}}}},
                               {'apiVersion': 'kubernetes.m.crossplane.io/v1alpha1',
                                'kind': 'Object',
                                'metadata': {'name': 'test-cp-backup-rbac'}},
                               {'apiVersion': 'kubernetes.m.crossplane.io/v1alpha1',
                                'kind': 'Object',
                                'metadata': {'name': 'test-cp-backup-rbac-binding'}}]}},
 {'name': 'with-license',
  'spec': {'compositionPath': 'apis/ctp/composition.yaml',
           'xrdPath': 'apis/ctp/definition.yaml',
           'validate': True,
           'timeoutSeconds': 60,
           'xr': {'apiVersion': 'gcp.platform.upbound.io/v1alpha1',
                  'kind': 'ControlPlane',
                  'metadata': {'name': 'test-cp'},
                  'spec': {'parameters': {'id': 'test-cp',
                                          'location': 'us-central1',
                                          'project': 'my-project',
                                          'version': '1.34',
                                          'nodes': {'count': 2,
                                                    'machineType': 'e2-standard-2'},
                                          'backup': {'enabled': 'yes',
                                                     'location': 'mybackup001'},
                                          'license': {'secretRef': {'name': 'uxp-license',
                                                                    'namespace': 'default'}}}}},
           'assertResources': [{'apiVersion': 'kubernetes.m.crossplane.io/v1alpha1',
                                'kind': 'Object',
                                'metadata': {'name': 'test-cp-uxp-license-secret'}},
                               {'apiVersion': 'kubernetes.m.crossplane.io/v1alpha1',
                                'kind': 'Object',
                                'metadata': {'name': 'test-cp-uxp-license'},
                                'spec': {'forProvider': {'manifest': {'kind': 'License',
                                                                      'metadata': {'name': 'uxp'}}}}}]}},
 {'name': 'no-backup',
  'spec': {'compositionPath': 'apis/ctp/composition.yaml',
           'xrdPath': 'apis/ctp/definition.yaml',
           'validate': True,
           'timeoutSeconds': 60,
           'xr': {'apiVersion': 'gcp.platform.upbound.io/v1alpha1',
                  'kind': 'ControlPlane',
                  'metadata': {'name': 'test-cp'},
                  'spec': {'parameters': {'id': 'test-cp',
                                          'location': 'us-central1',
                                          'project': 'my-project',
                                          'version': '1.34',
                                          'nodes': {'count': 2,
                                                    'machineType': 'e2-standard-2'}}}},
           'assertResources': [{'apiVersion': 'gcp.platform.upbound.io/v1alpha1',
                                'kind': 'Network',
                                'metadata': {'name': 'test-cp'}},
                               {'apiVersion': 'gcp.platform.upbound.io/v1alpha1',
                                'kind': 'GKE',
                                'metadata': {'name': 'test-cp'}},
                               {'apiVersion': 'helm.m.crossplane.io/v1beta1',
                                'kind': 'Release',
                                'metadata': {'name': 'test-cp-uxp'}}]}},
 {'name': 'with-schedule',
  'spec': {'compositionPath': 'apis/ctp/composition.yaml',
           'xrdPath': 'apis/ctp/definition.yaml',
           'validate': True,
           'timeoutSeconds': 60,
           'xr': {'apiVersion': 'gcp.platform.upbound.io/v1alpha1',
                  'kind': 'ControlPlane',
                  'metadata': {'name': 'test-cp'},
                  'spec': {'parameters': {'id': 'test-cp',
                                          'location': 'us-central1',
                                          'project': 'my-project',
                                          'version': '1.34',
                                          'nodes': {'count': 2,
                                                    'machineType': 'e2-standard-2'},
                                          'backup': {'enabled': 'yes',
                                                     'location': 'mybackup001',
                                                     'schedule': '@daily'}}}},
           'assertResources': [{'apiVersion': 'kubernetes.m.crossplane.io/v1alpha1',
                                'kind': 'Object',
                                'metadata': {'name': 'test-cp-backup-config'}},
                               {'apiVersion': 'kubernetes.m.crossplane.io/v1alpha1',
                                'kind': 'Object',
                                'metadata': {'name': 'test-cp-backup-schedule'},
                                'spec': {'forProvider': {'manifest': {'kind': 'BackupSchedule',
                                                                      'spec': {'schedule': '@daily',
                                                                               'configRef': {'name': 'test-cp-backup'}}}}}}]}},
 {'name': 'with-vpa',
  'spec': {'compositionPath': 'apis/ctp/composition.yaml',
           'xrdPath': 'apis/ctp/definition.yaml',
           'validate': True,
           'timeoutSeconds': 60,
           'xr': {'apiVersion': 'gcp.platform.upbound.io/v1alpha1',
                  'kind': 'ControlPlane',
                  'metadata': {'name': 'test-cp'},
                  'spec': {'parameters': {'id': 'test-cp',
                                          'location': 'us-central1',
                                          'project': 'my-project',
                                          'version': '1.34',
                                          'nodes': {'count': 2,
                                                    'machineType': 'e2-standard-2'},
                                          'providerVerticalPodAutoscaling': {'enabled': 'yes',
                                                                             'minCpu': '500m',
                                                                             'maxCpu': '2',
                                                                             'minMemory': '100Mi',
                                                                             'maxMemory': '4000Mi'}}}},
           'assertResources': [{'apiVersion': 'helm.m.crossplane.io/v1beta1',
                                'kind': 'Release',
                                'metadata': {'name': 'test-cp-vpa'},
                                'spec': {'forProvider': {'chart': {'name': 'vpa',
                                                                   'repository': 'https://charts.fairwinds.com/stable',
                                                                   'version': '4.10.1'},
                                                         'namespace': 'kube-system'}}}]}},
 {'name': 'with-vpa-deployed',
  'spec': {'compositionPath': 'apis/ctp/composition.yaml',
           'xrdPath': 'apis/ctp/definition.yaml',
           'validate': True,
           'timeoutSeconds': 60,
           'xr': {'apiVersion': 'gcp.platform.upbound.io/v1alpha1',
                  'kind': 'ControlPlane',
                  'metadata': {'name': 'test-cp'},
                  'spec': {'parameters': {'id': 'test-cp',
                                          'location': 'us-central1',
                                          'project': 'my-project',
                                          'version': '1.34',
                                          'nodes': {'count': 2,
                                                    'machineType': 'e2-standard-2'},
                                          'providerVerticalPodAutoscaling': {'enabled': 'yes',
                                                                             'minCpu': '500m',
                                                                             'maxCpu': '2',
                                                                             'minMemory': '100Mi',
                                                                             'maxMemory': '4000Mi'}}}},
           'observedResources': [{'apiVersion': 'helm.m.crossplane.io/v1beta1',
                                  'kind': 'Release',
                                  'metadata': {'name': 'test-cp-vpa',
                                               'namespace': 'default',
                                               'annotations': {'crossplane.io/composition-resource-name': 'vpa-release'}},
                                  'spec': {'forProvider': {'chart': {'name': 'vpa',
                                                                     'repository': 'https://charts.fairwinds.com/stable',
                                                                     'version': '4.10.1'}}},
                                  'status': {'atProvider': {'state': 'deployed'}}}],
           'assertResources': [{'apiVersion': 'kubernetes.m.crossplane.io/v1alpha1',
                                'kind': 'Object',
                                'metadata': {'name': 'test-cp-upbound-runtime-config'},
                                'spec': {'forProvider': {'manifest': {'kind': 'UpboundRuntimeConfig',
                                                                      'spec': {'capabilities': ['ProviderVPA']}}}}},
                               {'apiVersion': 'helm.m.crossplane.io/v1beta1',
                                'kind': 'Release',
                                'metadata': {'name': 'test-cp-uxp'},
                                'spec': {'forProvider': {'values': {'upbound': {'manager': {'args': ['--enable-provider-vpa']}}}}}}]}},
 {'name': 'backup-uxp-deployed',
  'spec': {'compositionPath': 'apis/ctp/composition.yaml',
           'xrdPath': 'apis/ctp/definition.yaml',
           'validate': True,
           'timeoutSeconds': 60,
           'xr': {'apiVersion': 'gcp.platform.upbound.io/v1alpha1',
                  'kind': 'ControlPlane',
                  'metadata': {'name': 'test-cp'},
                  'spec': {'parameters': {'id': 'test-cp',
                                          'location': 'us-central1',
                                          'project': 'my-project',
                                          'version': '1.34',
                                          'nodes': {'count': 2,
                                                    'machineType': 'e2-standard-2'},
                                          'backup': {'enabled': 'yes',
                                                     'location': 'mybackup001'}}}},
           'observedResources': [{'apiVersion': 'helm.m.crossplane.io/v1beta1',
                                  'kind': 'Release',
                                  'metadata': {'name': 'test-cp-uxp',
                                               'namespace': 'default',
                                               'annotations': {'crossplane.io/composition-resource-name': 'uxp-release'}},
                                  'spec': {'forProvider': {'chart': {'name': 'crossplane',
                                                                     'repository': 'oci://xpkg.upbound.io/upbound',
                                                                     'version': '2.2.1-up.1'}}},
                                  'status': {'atProvider': {'state': 'deployed'}}}],
           'assertResources': [{'apiVersion': 'cloudplatform.gcp.m.upbound.io/v1beta1',
                                'kind': 'ServiceAccount',
                                'metadata': {'name': 'test-cp-backup-identity',
                                             'annotations': {'crossplane.io/external-name': 'test-cp-backup'}}},
                               {'apiVersion': 'cloudplatform.gcp.m.upbound.io/v1beta1',
                                'kind': 'ServiceAccountIAMMember',
                                'metadata': {'name': 'test-cp-backup-wi-binding'},
                                'spec': {'forProvider': {'serviceAccountId': 'projects/my-project/serviceAccounts/test-cp-backup@my-project.iam.gserviceaccount.com',
                                                         'role': 'roles/iam.workloadIdentityUser',
                                                         'member': 'serviceAccount:my-project.svc.id.goog[crossplane-system/upbound-controller-manager]'}}},
                               {'apiVersion': 'storage.gcp.m.upbound.io/v1beta1',
                                'kind': 'BucketIAMMember',
                                'metadata': {'name': 'test-cp-backup-bucket-role'},
                                'spec': {'forProvider': {'role': 'roles/storage.objectAdmin',
                                                         'member': 'serviceAccount:test-cp-backup@my-project.iam.gserviceaccount.com'}}},
                               {'apiVersion': 'kubernetes.m.crossplane.io/v1alpha1',
                                'kind': 'Object',
                                'metadata': {'name': 'test-cp-backup-sa'},
                                'spec': {'forProvider': {'manifest': {'kind': 'ServiceAccount',
                                                                      'metadata': {'name': 'upbound-controller-manager',
                                                                                   'namespace': 'crossplane-system',
                                                                                   'annotations': {'iam.gke.io/gcp-service-account': 'test-cp-backup@my-project.iam.gserviceaccount.com'}}}}}},
                               {'apiVersion': 'kubernetes.m.crossplane.io/v1alpha1',
                                'kind': 'Object',
                                'metadata': {'name': 'test-cp-controller-restart'},
                                'spec': {'forProvider': {'manifest': {'kind': 'Deployment',
                                                                      'metadata': {'name': 'upbound-controller-manager',
                                                                                   'namespace': 'crossplane-system'}}}}}]}},
 {'name': 'uxp-targets-crossplane-system',
  'spec': {'compositionPath': 'apis/ctp/composition.yaml',
           'xrdPath': 'apis/ctp/definition.yaml',
           'validate': True,
           'timeoutSeconds': 60,
           'xr': {'apiVersion': 'gcp.platform.upbound.io/v1alpha1',
                  'kind': 'ControlPlane',
                  'metadata': {'name': 'test-cp'},
                  'spec': {'parameters': {'id': 'test-cp',
                                          'location': 'us-central1',
                                          'project': 'my-project',
                                          'version': '1.34',
                                          'nodes': {'count': 2,
                                                    'machineType': 'e2-standard-2'}}}},
           'assertResources': [{'apiVersion': 'helm.m.crossplane.io/v1beta1',
                                'kind': 'Release',
                                'metadata': {'name': 'test-cp-uxp'},
                                'spec': {'forProvider': {'namespace': 'crossplane-system',
                                                         'chart': {'name': 'crossplane'}}}}]}},
 {'name': 'vpa-and-knative-merged',
  'spec': {'compositionPath': 'apis/ctp/composition.yaml',
           'xrdPath': 'apis/ctp/definition.yaml',
           'validate': True,
           'timeoutSeconds': 60,
           'xr': {'apiVersion': 'gcp.platform.upbound.io/v1alpha1',
                  'kind': 'ControlPlane',
                  'metadata': {'name': 'test-cp'},
                  'spec': {'parameters': {'id': 'test-cp',
                                          'location': 'us-central1',
                                          'project': 'my-project',
                                          'version': '1.34',
                                          'nodes': {'count': 2,
                                                    'machineType': 'e2-standard-2'},
                                          'providerVerticalPodAutoscaling': {'enabled': 'yes'},
                                          'knative': {'enabled': 'yes'}}}},
           'observedResources': [{'apiVersion': 'helm.m.crossplane.io/v1beta1',
                                  'kind': 'Release',
                                  'metadata': {'name': 'test-cp-vpa',
                                               'namespace': 'default',
                                               'annotations': {'crossplane.io/composition-resource-name': 'vpa-release'}},
                                  'spec': {'forProvider': {'chart': {'name': 'vpa',
                                                                     'repository': 'https://charts.fairwinds.com/stable',
                                                                     'version': '4.10.1'}}},
                                  'status': {'atProvider': {'state': 'deployed'}}},
                                 {'apiVersion': 'helm.m.crossplane.io/v1beta1',
                                  'kind': 'Release',
                                  'metadata': {'name': 'test-cp-certmanager',
                                               'namespace': 'default',
                                               'annotations': {'crossplane.io/composition-resource-name': 'certmanager-release'}},
                                  'spec': {'forProvider': {'chart': {'name': 'cert-manager',
                                                                     'repository': 'https://charts.jetstack.io',
                                                                     'version': 'v1.20.3'}}},
                                  'status': {'atProvider': {'state': 'deployed'}}},
                                 {'apiVersion': 'helm.m.crossplane.io/v1beta1',
                                  'kind': 'Release',
                                  'metadata': {'name': 'test-cp-knative-operator',
                                               'namespace': 'default',
                                               'annotations': {'crossplane.io/composition-resource-name': 'knative-operator-release'}},
                                  'spec': {'forProvider': {'chart': {'name': 'knative-operator',
                                                                     'repository': 'https://knative.github.io/operator',
                                                                     'version': 'v1.21.1'}}},
                                  'status': {'atProvider': {'state': 'deployed'}}},
                                 {'apiVersion': 'kubernetes.m.crossplane.io/v1alpha1',
                                  'kind': 'Object',
                                  'metadata': {'name': 'test-cp-knative-serving-cr',
                                               'namespace': 'default',
                                               'annotations': {'crossplane.io/composition-resource-name': 'knative-serving-cr'}},
                                  'spec': {'providerConfigRef': {'name': 'test-cp'}},
                                  'status': {'atProvider': {'manifest': {'status': {'conditions': [{'type': 'Ready',
                                                                                                    'status': 'True'}]}}}}}],
           'assertResources': [{'apiVersion': 'kubernetes.m.crossplane.io/v1alpha1',
                                'kind': 'Object',
                                'metadata': {'name': 'test-cp-upbound-runtime-config'},
                                'spec': {'forProvider': {'manifest': {'spec': {'capabilities': ['ProviderVPA',
                                                                                                'FunctionKnativeRuntime']}}}}},
                               {'apiVersion': 'helm.m.crossplane.io/v1beta1',
                                'kind': 'Release',
                                'metadata': {'name': 'test-cp-uxp'},
                                'spec': {'forProvider': {'values': {'upbound': {'manager': {'args': ['--enable-provider-vpa',
                                                                                                     '--enable-knative-runtime']}}}}}}]}},
 {'name': 'with-knative',
  'spec': {'compositionPath': 'apis/ctp/composition.yaml',
           'xrdPath': 'apis/ctp/definition.yaml',
           'validate': True,
           'timeoutSeconds': 60,
           'xr': {'apiVersion': 'gcp.platform.upbound.io/v1alpha1',
                  'kind': 'ControlPlane',
                  'metadata': {'name': 'test-cp'},
                  'spec': {'parameters': {'id': 'test-cp',
                                          'location': 'us-central1',
                                          'project': 'my-project',
                                          'version': '1.34',
                                          'nodes': {'count': 2,
                                                    'machineType': 'e2-standard-2'},
                                          'knative': {'enabled': 'yes'}}}},
           'assertResources': [{'apiVersion': 'helm.m.crossplane.io/v1beta1',
                                'kind': 'Release',
                                'metadata': {'name': 'test-cp-certmanager'},
                                'spec': {'forProvider': {'chart': {'name': 'cert-manager',
                                                                   'repository': 'https://charts.jetstack.io'}}}},
                               {'apiVersion': 'helm.m.crossplane.io/v1beta1',
                                'kind': 'Release',
                                'metadata': {'name': 'test-cp-knative-operator'},
                                'spec': {'forProvider': {'chart': {'name': 'knative-operator',
                                                                   'repository': 'https://knative.github.io/operator'}}}}]}},
 {'name': 'with-install-from',
  'spec': {'compositionPath': 'apis/ctp/composition.yaml',
           'xrdPath': 'apis/ctp/definition.yaml',
           'validate': True,
           'timeoutSeconds': 60,
           'xr': {'apiVersion': 'gcp.platform.upbound.io/v1alpha1',
                  'kind': 'ControlPlane',
                  'metadata': {'name': 'test-cp'},
                  'spec': {'parameters': {'id': 'test-cp',
                                          'location': 'us-central1',
                                          'project': 'my-project',
                                          'version': '1.34',
                                          'nodes': {'count': 2,
                                                    'machineType': 'e2-standard-4'},
                                          'backup': {'enabled': 'yes',
                                                     'location': 'newcpbackup',
                                                     'installFrom': {'location': 'oldcpbackup',
                                                                     'name': 'old-cp-backup-002'}}}}},
           'assertResources': [{'apiVersion': 'storage.gcp.m.upbound.io/v1beta1',
                                'kind': 'Bucket',
                                'metadata': {'name': 'newcpbackup'}},
                               {'apiVersion': 'kubernetes.m.crossplane.io/v1alpha1',
                                'kind': 'Object',
                                'metadata': {'name': 'test-cp-backup-config'},
                                'spec': {'forProvider': {'manifest': {'spec': {'objectStorage': {'provider': 'GCP',
                                                                                                 'bucket': 'newcpbackup'}}}}}}]}},
 {'name': 'with-k8gb',
  'spec': {'compositionPath': 'apis/ctp/composition.yaml',
           'xrdPath': 'apis/ctp/definition.yaml',
           'validate': True,
           'timeoutSeconds': 60,
           'xr': {'apiVersion': 'gcp.platform.upbound.io/v1alpha1',
                  'kind': 'ControlPlane',
                  'metadata': {'name': 'test-cp'},
                  'spec': {'parameters': {'id': 'test-cp',
                                          'location': 'us-central1',
                                          'project': 'my-project',
                                          'version': '1.34',
                                          'nodes': {'count': 2,
                                                    'machineType': 'e2-standard-2'},
                                          'k8gb': {'enabled': 'yes',
                                                   'dnsZone': 'gslb.example.com',
                                                   'parentZone': 'example.com'}}}},
           'observedResources': [{'apiVersion': 'compute.gcp.m.upbound.io/v1beta1',
                                  'kind': 'Address',
                                  'metadata': {'name': 'test-cp-k8gb-address',
                                               'namespace': 'default',
                                               'annotations': {'crossplane.io/composition-resource-name': 'k8gb-address'}},
                                  'status': {'atProvider': {'address': '203.0.113.10'}}}],
           'assertResources': [{'apiVersion': 'compute.gcp.m.upbound.io/v1beta1',
                                'kind': 'Address',
                                'metadata': {'name': 'test-cp-k8gb-address'},
                                'spec': {'forProvider': {'addressType': 'EXTERNAL',
                                                         'region': 'us-central1',
                                                         'networkTier': 'PREMIUM'}}},
                               {'apiVersion': 'helm.m.crossplane.io/v1beta1',
                                'kind': 'Release',
                                'metadata': {'name': 'test-cp-k8gb',
                                             'annotations': {'crossplane.io/external-name': 'k8gb'}},
                                'spec': {'forProvider': {'chart': {'name': 'k8gb',
                                                                   'repository': 'https://www.k8gb.io',
                                                                   'version': 'v0.20.0'},
                                                         'namespace': 'k8gb',
                                                         'values': {'k8gb': {'clusterGeoTag': 'gcp-us-central1-test-cp',
                                                                             'dnsZones': [{'loadBalancedZone': 'gslb.example.com',
                                                                                           'parentZone': 'example.com'}]},
                                                                    'extdns': {'enabled': False},
                                                                    'coredns': {'serviceType': 'LoadBalancer',
                                                                                'servers': [{'zones': [{'zone': '.',
                                                                                                        'use_tcp': False}],
                                                                                             'port': 5353,
                                                                                             'servicePort': 53,
                                                                                             'plugins': [{'name': 'prometheus',
                                                                                                          'parameters': '0.0.0.0:9153'}]}],
                                                                                'service': {'annotations': {'cloud.google.com/l4-rbs': 'enabled'},
                                                                                            'loadBalancerIP': '203.0.113.10'}}}}}},
                               {'apiVersion': 'kubernetes.m.crossplane.io/v1alpha1',
                                'kind': 'Object',
                                'metadata': {'name': 'test-cp-k8gb-coredns'},
                                'spec': {'managementPolicies': ['Observe'],
                                         'forProvider': {'manifest': {'kind': 'Service',
                                                                      'metadata': {'name': 'k8gb-coredns',
                                                                                   'namespace': 'k8gb'}}}}},
                               {'apiVersion': 'helm.m.crossplane.io/v1beta1',
                                'kind': 'Release',
                                'metadata': {'name': 'test-cp-envoy-gateway'},
                                'spec': {'forProvider': {'chart': {'name': 'gateway-helm',
                                                                   'repository': 'oci://docker.io/envoyproxy',
                                                                   'version': 'v1.8.2'},
                                                         'namespace': 'envoy-gateway-system'}}},
                               {'apiVersion': 'protection.crossplane.io/v1beta1',
                                'kind': 'Usage',
                                'metadata': {'name': 'test-cp-usage-envoy-gateway-gke'},
                                'spec': {'of': {'kind': 'GKE'},
                                         'by': {'kind': 'Release'}}},
                               {'apiVersion': 'protection.crossplane.io/v1beta1',
                                'kind': 'Usage',
                                'metadata': {'name': 'test-cp-usage-k8gb-gke'},
                                'spec': {'of': {'kind': 'GKE'},
                                         'by': {'kind': 'Release'}}},
                               {'apiVersion': 'protection.crossplane.io/v1beta1',
                                'kind': 'Usage',
                                'metadata': {'name': 'test-cp-usage-k8gb-coredns-gke'},
                                'spec': {'of': {'kind': 'GKE'},
                                         'by': {'kind': 'Object'}}},
                               {'apiVersion': 'protection.crossplane.io/v1beta1',
                                'kind': 'Usage',
                                'metadata': {'name': 'test-cp-usage-k8gb-address-release'},
                                'spec': {'of': {'kind': 'Address',
                                                'resourceRef': {'name': 'test-cp-k8gb-address'}},
                                         'by': {'kind': 'Release',
                                                'resourceRef': {'name': 'test-cp-k8gb'}}}}]}},
 {'name': 'with-k8gb-address-pending',
  'spec': {'compositionPath': 'apis/ctp/composition.yaml',
           'xrdPath': 'apis/ctp/definition.yaml',
           'validate': True,
           'timeoutSeconds': 60,
           'xr': {'apiVersion': 'gcp.platform.upbound.io/v1alpha1',
                  'kind': 'ControlPlane',
                  'metadata': {'name': 'test-cp'},
                  'spec': {'parameters': {'id': 'test-cp',
                                          'location': 'us-central1',
                                          'project': 'my-project',
                                          'version': '1.34',
                                          'nodes': {'count': 2,
                                                    'machineType': 'e2-standard-2'},
                                          'k8gb': {'enabled': 'yes',
                                                   'dnsZone': 'gslb.example.com',
                                                   'parentZone': 'example.com'}}}},
           'assertResources': [{'apiVersion': 'compute.gcp.m.upbound.io/v1beta1',
                                'kind': 'Address',
                                'metadata': {'name': 'test-cp-k8gb-address'},
                                'spec': {'forProvider': {'addressType': 'EXTERNAL',
                                                         'region': 'us-central1',
                                                         'networkTier': 'PREMIUM'}}}]}},
 {'name': 'with-k8gb-endpoint',
  'spec': {'compositionPath': 'apis/ctp/composition.yaml',
           'xrdPath': 'apis/ctp/definition.yaml',
           'validate': True,
           'timeoutSeconds': 60,
           'xr': {'apiVersion': 'gcp.platform.upbound.io/v1alpha1',
                  'kind': 'ControlPlane',
                  'metadata': {'name': 'test-cp'},
                  'spec': {'parameters': {'id': 'test-cp',
                                          'location': 'us-central1',
                                          'project': 'my-project',
                                          'version': '1.34',
                                          'nodes': {'count': 2,
                                                    'machineType': 'e2-standard-2'},
                                          'k8gb': {'enabled': 'yes',
                                                   'dnsZone': 'gslb.example.com',
                                                   'parentZone': 'example.com'}}}},
           'observedResources': [{'apiVersion': 'kubernetes.m.crossplane.io/v1alpha1',
                                  'kind': 'Object',
                                  'metadata': {'name': 'test-cp-k8gb-coredns',
                                               'namespace': 'default',
                                               'annotations': {'crossplane.io/composition-resource-name': 'k8gb-coredns-observe'}},
                                  'status': {'atProvider': {'manifest': {'status': {'loadBalancer': {'ingress': [{'ip': '203.0.113.20'}]}}}}}},
                                 {'apiVersion': 'compute.gcp.m.upbound.io/v1beta1',
                                  'kind': 'Address',
                                  'metadata': {'name': 'test-cp-k8gb-address',
                                               'namespace': 'default',
                                               'annotations': {'crossplane.io/composition-resource-name': 'k8gb-address'}},
                                  'status': {'atProvider': {'address': '203.0.113.10'}}}],
           'assertResources': [{'apiVersion': 'gcp.platform.upbound.io/v1alpha1',
                                'kind': 'ControlPlane',
                                'metadata': {'name': 'test-cp'},
                                'status': {'controlplane': {'k8gb': {'enabled': 'yes',
                                                                     'coreDNSEndpoint': '203.0.113.20',
                                                                     'nsName': 'gslb-ns-gcp-us-central1-test-cp-gslb.example.com',
                                                                     'glueAddresses': ['203.0.113.10'],
                                                                     'delegationRecord': 'gslb.example.com. '
                                                                                         'NS '
                                                                                         'gslb-ns-gcp-us-central1-test-cp-gslb.example.com.\n'
                                                                                         'gslb-ns-gcp-us-central1-test-cp-gslb.example.com. '
                                                                                         'A '
                                                                                         '203.0.113.10'}}}}]}},
 {'name': 'with-argocd',
  'spec': {'compositionPath': 'apis/ctp/composition.yaml',
           'xrdPath': 'apis/ctp/definition.yaml',
           'validate': True,
           'timeoutSeconds': 60,
           'xr': {'apiVersion': 'gcp.platform.upbound.io/v1alpha1',
                  'kind': 'ControlPlane',
                  'metadata': {'name': 'test-cp'},
                  'spec': {'parameters': {'id': 'test-cp',
                                          'location': 'us-central1',
                                          'project': 'my-project',
                                          'version': '1.34',
                                          'nodes': {'count': 2,
                                                    'machineType': 'e2-standard-2'},
                                          'argocd': {'enabled': 'yes',
                                                     'hostname': 'argocd.example.com',
                                                     'url': 'https://github.com/example/apps'}}}},
           'assertResources': [{'apiVersion': 'helm.m.crossplane.io/v1beta1',
                                'kind': 'Release',
                                'metadata': {'name': 'test-cp-argocd',
                                             'annotations': {'crossplane.io/external-name': 'argocd'}},
                                'spec': {'forProvider': {'chart': {'name': 'argo-cd',
                                                                   'repository': 'https://argoproj.github.io/argo-helm'},
                                                         'namespace': 'argocd',
                                                         'values': {'configs': {'params': {'server.insecure': True}}}}}},
                               {'apiVersion': 'helm.m.crossplane.io/v1beta1',
                                'kind': 'Release',
                                'metadata': {'name': 'test-cp-envoy-gateway'}},
                               {'apiVersion': 'protection.crossplane.io/v1beta1',
                                'kind': 'Usage',
                                'metadata': {'name': 'test-cp-usage-argocd-gke'}},
                               {'apiVersion': 'protection.crossplane.io/v1beta1',
                                'kind': 'Usage',
                                'metadata': {'name': 'test-cp-usage-argocd-gateway-gke'}},
                               {'apiVersion': 'protection.crossplane.io/v1beta1',
                                'kind': 'Usage',
                                'metadata': {'name': 'test-cp-usage-argocd-httproute-gke'}}]}},
 {'name': 'with-argocd-deployed',
  'spec': {'compositionPath': 'apis/ctp/composition.yaml',
           'xrdPath': 'apis/ctp/definition.yaml',
           'validate': True,
           'timeoutSeconds': 60,
           'xr': {'apiVersion': 'gcp.platform.upbound.io/v1alpha1',
                  'kind': 'ControlPlane',
                  'metadata': {'name': 'test-cp'},
                  'spec': {'parameters': {'id': 'test-cp',
                                          'location': 'us-central1',
                                          'project': 'my-project',
                                          'version': '1.34',
                                          'nodes': {'count': 2,
                                                    'machineType': 'e2-standard-2'},
                                          'argocd': {'enabled': 'yes',
                                                     'hostname': 'argocd.example.com',
                                                     'url': 'https://github.com/example/apps'}}}},
           'observedResources': [{'apiVersion': 'helm.m.crossplane.io/v1beta1',
                                  'kind': 'Release',
                                  'metadata': {'name': 'test-cp-certmanager',
                                               'namespace': 'default',
                                               'annotations': {'crossplane.io/composition-resource-name': 'certmanager-release'}},
                                  'status': {'atProvider': {'state': 'deployed'}}},
                                 {'apiVersion': 'helm.m.crossplane.io/v1beta1',
                                  'kind': 'Release',
                                  'metadata': {'name': 'test-cp-argocd',
                                               'namespace': 'default',
                                               'annotations': {'crossplane.io/composition-resource-name': 'argocd-release'}},
                                  'status': {'atProvider': {'state': 'deployed'}}},
                                 {'apiVersion': 'helm.m.crossplane.io/v1beta1',
                                  'kind': 'Release',
                                  'metadata': {'name': 'test-cp-envoy-gateway',
                                               'namespace': 'default',
                                               'annotations': {'crossplane.io/composition-resource-name': 'envoy-gateway-release'}},
                                  'status': {'atProvider': {'state': 'deployed'}}}],
           'assertResources': [{'apiVersion': 'kubernetes.m.crossplane.io/v1alpha1',
                                'kind': 'Object',
                                'metadata': {'name': 'test-cp-argocd-issuer'},
                                'spec': {'forProvider': {'manifest': {'kind': 'ClusterIssuer',
                                                                      'metadata': {'name': 'argocd-selfsigned'}}}}},
                               {'apiVersion': 'kubernetes.m.crossplane.io/v1alpha1',
                                'kind': 'Object',
                                'metadata': {'name': 'test-cp-argocd-cert'},
                                'spec': {'forProvider': {'manifest': {'kind': 'Certificate',
                                                                      'spec': {'secretName': 'argocd-server-tls',
                                                                               'issuerRef': {'name': 'argocd-selfsigned',
                                                                                             'kind': 'ClusterIssuer'}}}}}},
                               {'apiVersion': 'kubernetes.m.crossplane.io/v1alpha1',
                                'kind': 'Object',
                                'metadata': {'name': 'test-cp-argocd-app'},
                                'spec': {'forProvider': {'manifest': {'kind': 'Application',
                                                                      'spec': {'source': {'repoURL': 'https://github.com/example/apps',
                                                                                          'path': '.',
                                                                                          'targetRevision': 'HEAD'}}}}}},
                               {'apiVersion': 'kubernetes.m.crossplane.io/v1alpha1',
                                'kind': 'Object',
                                'metadata': {'name': 'test-cp-argocd-gateway'},
                                'spec': {'forProvider': {'manifest': {'kind': 'Gateway',
                                                                      'spec': {'gatewayClassName': 'eg',
                                                                               'listeners': [{'name': 'https',
                                                                                              'protocol': 'HTTPS',
                                                                                              'port': 443,
                                                                                              'hostname': 'argocd.example.com',
                                                                                              'tls': {'mode': 'Terminate',
                                                                                                      'certificateRefs': [{'name': 'argocd-server-tls'}]}}]}}}}},
                               {'apiVersion': 'kubernetes.m.crossplane.io/v1alpha1',
                                'kind': 'Object',
                                'metadata': {'name': 'test-cp-argocd-httproute'},
                                'spec': {'forProvider': {'manifest': {'kind': 'HTTPRoute',
                                                                      'spec': {'parentRefs': [{'name': 'argocd',
                                                                                               'sectionName': 'https'}],
                                                                               'hostnames': ['argocd.example.com'],
                                                                               'rules': [{'backendRefs': [{'name': 'argocd-server',
                                                                                                           'port': 80}]}]}}}}}]}},
 {'name': 'with-envoy-gateway',
  'spec': {'compositionPath': 'apis/ctp/composition.yaml',
           'xrdPath': 'apis/ctp/definition.yaml',
           'validate': True,
           'timeoutSeconds': 60,
           'xr': {'apiVersion': 'gcp.platform.upbound.io/v1alpha1',
                  'kind': 'ControlPlane',
                  'metadata': {'name': 'test-cp'},
                  'spec': {'parameters': {'id': 'test-cp',
                                          'location': 'us-central1',
                                          'project': 'my-project',
                                          'version': '1.34',
                                          'nodes': {'count': 2,
                                                    'machineType': 'e2-standard-2'},
                                          'k8gb': {'enabled': 'yes',
                                                   'dnsZone': 'gslb.example.com',
                                                   'parentZone': 'example.com'}}}},
           'observedResources': [{'apiVersion': 'helm.m.crossplane.io/v1beta1',
                                  'kind': 'Release',
                                  'metadata': {'name': 'test-cp-envoy-gateway',
                                               'namespace': 'default',
                                               'annotations': {'crossplane.io/composition-resource-name': 'envoy-gateway-release'}},
                                  'status': {'atProvider': {'state': 'deployed'}}}],
           'assertResources': [{'apiVersion': 'helm.m.crossplane.io/v1beta1',
                                'kind': 'Release',
                                'metadata': {'name': 'test-cp-envoy-gateway'},
                                'spec': {'forProvider': {'chart': {'name': 'gateway-helm',
                                                                   'repository': 'oci://docker.io/envoyproxy',
                                                                   'version': 'v1.8.2'},
                                                         'namespace': 'envoy-gateway-system'}}},
                               {'apiVersion': 'kubernetes.m.crossplane.io/v1alpha1',
                                'kind': 'Object',
                                'metadata': {'name': 'test-cp-envoy-proxy-config'},
                                'spec': {'forProvider': {'manifest': {'kind': 'EnvoyProxy',
                                                                      'spec': {'provider': {'kubernetes': {'envoyService': {'type': 'LoadBalancer'}}}}}}}},
                               {'apiVersion': 'kubernetes.m.crossplane.io/v1alpha1',
                                'kind': 'Object',
                                'metadata': {'name': 'test-cp-gateway-class'},
                                'spec': {'forProvider': {'manifest': {'kind': 'GatewayClass',
                                                                      'spec': {'controllerName': 'gateway.envoyproxy.io/gatewayclass-controller'}}}}}]}},
 {'name': 'namespaced-core',
  'spec': {'compositionPath': 'apis/ctp/composition.yaml',
           'xrdPath': 'apis/ctp/definition.yaml',
           'validate': True,
           'timeoutSeconds': 60,
           'xr': {'apiVersion': 'gcp.platform.upbound.io/v1alpha1',
                  'kind': 'ControlPlane',
                  'metadata': {'name': 'test-cp', 'namespace': 'platform'},
                  'spec': {'parameters': {'id': 'test-cp',
                                          'location': 'us-central1',
                                          'project': 'my-project',
                                          'version': '1.34',
                                          'nodes': {'count': 2,
                                                    'machineType': 'e2-standard-2'}}}},
           'assertResources': [{'apiVersion': 'gcp.platform.upbound.io/v1alpha1',
                                'kind': 'Network',
                                'metadata': {'name': 'test-cp',
                                             'namespace': 'platform'}},
                               {'apiVersion': 'gcp.platform.upbound.io/v1alpha1',
                                'kind': 'GKE',
                                'metadata': {'name': 'test-cp',
                                             'namespace': 'platform'}},
                               {'apiVersion': 'helm.m.crossplane.io/v1beta1',
                                'kind': 'Release',
                                'metadata': {'name': 'test-cp-uxp',
                                             'namespace': 'platform'},
                                'spec': {'forProvider': {'namespace': 'crossplane-system'}}},
                               {'apiVersion': 'helm.m.crossplane.io/v1beta1',
                                'kind': 'Release',
                                'metadata': {'name': 'test-cp-certmanager',
                                             'namespace': 'platform'},
                                'spec': {'forProvider': {'namespace': 'cert-manager'}}},
                               {'apiVersion': 'protection.crossplane.io/v1beta1',
                                'kind': 'Usage',
                                'metadata': {'name': 'test-cp-usage-gke-network',
                                             'namespace': 'platform'},
                                'spec': {'of': {'kind': 'Network',
                                                'resourceRef': {'name': 'test-cp',
                                                                'namespace': 'platform'}}}}]}},
 {'name': 'default-namespace-fallback',
  'spec': {'compositionPath': 'apis/ctp/composition.yaml',
           'xrdPath': 'apis/ctp/definition.yaml',
           'validate': True,
           'timeoutSeconds': 60,
           'xr': {'apiVersion': 'gcp.platform.upbound.io/v1alpha1',
                  'kind': 'ControlPlane',
                  'metadata': {'name': 'test-cp', 'namespace': 'default'},
                  'spec': {'parameters': {'id': 'test-cp',
                                          'location': 'us-central1',
                                          'project': 'my-project',
                                          'version': '1.34',
                                          'nodes': {'count': 2,
                                                    'machineType': 'e2-standard-2'}}}},
           'assertResources': [{'apiVersion': 'gcp.platform.upbound.io/v1alpha1',
                                'kind': 'GKE',
                                'metadata': {'name': 'test-cp',
                                             'namespace': 'default'}}]}},
 {'name': 'namespaced-backup',
  'spec': {'compositionPath': 'apis/ctp/composition.yaml',
           'xrdPath': 'apis/ctp/definition.yaml',
           'validate': True,
           'timeoutSeconds': 60,
           'xr': {'apiVersion': 'gcp.platform.upbound.io/v1alpha1',
                  'kind': 'ControlPlane',
                  'metadata': {'name': 'test-cp', 'namespace': 'platform'},
                  'spec': {'parameters': {'id': 'test-cp',
                                          'location': 'us-central1',
                                          'project': 'my-project',
                                          'version': '1.34',
                                          'nodes': {'count': 2,
                                                    'machineType': 'e2-standard-2'},
                                          'backup': {'enabled': 'yes',
                                                     'location': 'mybackup001'}}}},
           'observedResources': [{'apiVersion': 'helm.m.crossplane.io/v1beta1',
                                  'kind': 'Release',
                                  'metadata': {'name': 'test-cp-uxp',
                                               'namespace': 'platform',
                                               'annotations': {'crossplane.io/composition-resource-name': 'uxp-release'}},
                                  'status': {'atProvider': {'state': 'deployed'}}}],
           'assertResources': [{'apiVersion': 'storage.gcp.m.upbound.io/v1beta1',
                                'kind': 'Bucket',
                                'metadata': {'name': 'mybackup001',
                                             'namespace': 'platform'}},
                               {'apiVersion': 'kubernetes.m.crossplane.io/v1alpha1',
                                'kind': 'Object',
                                'metadata': {'name': 'test-cp-backup-config',
                                             'namespace': 'platform'}},
                               {'apiVersion': 'cloudplatform.gcp.m.upbound.io/v1beta1',
                                'kind': 'ServiceAccount',
                                'metadata': {'name': 'test-cp-backup-identity',
                                             'namespace': 'platform'}},
                               {'apiVersion': 'kubernetes.m.crossplane.io/v1alpha1',
                                'kind': 'Object',
                                'metadata': {'name': 'test-cp-backup-sa',
                                             'namespace': 'platform'},
                                'spec': {'forProvider': {'manifest': {'metadata': {'namespace': 'crossplane-system'}}}}}]}},
 {'name': 'namespaced-k8gb',
  'spec': {'compositionPath': 'apis/ctp/composition.yaml',
           'xrdPath': 'apis/ctp/definition.yaml',
           'validate': True,
           'timeoutSeconds': 60,
           'xr': {'apiVersion': 'gcp.platform.upbound.io/v1alpha1',
                  'kind': 'ControlPlane',
                  'metadata': {'name': 'test-cp', 'namespace': 'platform'},
                  'spec': {'parameters': {'id': 'test-cp',
                                          'location': 'us-central1',
                                          'project': 'my-project',
                                          'version': '1.34',
                                          'nodes': {'count': 2,
                                                    'machineType': 'e2-standard-2'},
                                          'k8gb': {'enabled': 'yes',
                                                   'dnsZone': 'gslb.example.com',
                                                   'parentZone': 'example.com'}}}},
           'observedResources': [{'apiVersion': 'compute.gcp.m.upbound.io/v1beta1',
                                  'kind': 'Address',
                                  'metadata': {'name': 'test-cp-k8gb-address',
                                               'namespace': 'platform',
                                               'annotations': {'crossplane.io/composition-resource-name': 'k8gb-address'}},
                                  'status': {'atProvider': {'address': '203.0.113.10'}}}],
           'assertResources': [{'apiVersion': 'helm.m.crossplane.io/v1beta1',
                                'kind': 'Release',
                                'metadata': {'name': 'test-cp-k8gb',
                                             'namespace': 'platform'},
                                'spec': {'forProvider': {'namespace': 'k8gb'}}},
                               {'apiVersion': 'kubernetes.m.crossplane.io/v1alpha1',
                                'kind': 'Object',
                                'metadata': {'name': 'test-cp-k8gb-coredns',
                                             'namespace': 'platform'},
                                'spec': {'forProvider': {'manifest': {'metadata': {'namespace': 'k8gb'}}}}},
                               {'apiVersion': 'helm.m.crossplane.io/v1beta1',
                                'kind': 'Release',
                                'metadata': {'name': 'test-cp-envoy-gateway',
                                             'namespace': 'platform'},
                                'spec': {'forProvider': {'namespace': 'envoy-gateway-system'}}}]}},
 {'name': 'namespaced-argocd',
  'spec': {'compositionPath': 'apis/ctp/composition.yaml',
           'xrdPath': 'apis/ctp/definition.yaml',
           'validate': True,
           'timeoutSeconds': 60,
           'xr': {'apiVersion': 'gcp.platform.upbound.io/v1alpha1',
                  'kind': 'ControlPlane',
                  'metadata': {'name': 'test-cp', 'namespace': 'platform'},
                  'spec': {'parameters': {'id': 'test-cp',
                                          'location': 'us-central1',
                                          'project': 'my-project',
                                          'version': '1.34',
                                          'nodes': {'count': 2,
                                                    'machineType': 'e2-standard-2'},
                                          'argocd': {'enabled': 'yes',
                                                     'hostname': 'argocd.example.com',
                                                     'url': 'https://github.com/example/apps'}}}},
           'observedResources': [{'apiVersion': 'helm.m.crossplane.io/v1beta1',
                                  'kind': 'Release',
                                  'metadata': {'name': 'test-cp-certmanager',
                                               'namespace': 'platform',
                                               'annotations': {'crossplane.io/composition-resource-name': 'certmanager-release'}},
                                  'status': {'atProvider': {'state': 'deployed'}}},
                                 {'apiVersion': 'helm.m.crossplane.io/v1beta1',
                                  'kind': 'Release',
                                  'metadata': {'name': 'test-cp-argocd',
                                               'namespace': 'platform',
                                               'annotations': {'crossplane.io/composition-resource-name': 'argocd-release'}},
                                  'status': {'atProvider': {'state': 'deployed'}}}],
           'assertResources': [{'apiVersion': 'helm.m.crossplane.io/v1beta1',
                                'kind': 'Release',
                                'metadata': {'name': 'test-cp-argocd',
                                             'namespace': 'platform'},
                                'spec': {'forProvider': {'namespace': 'argocd'}}},
                               {'apiVersion': 'kubernetes.m.crossplane.io/v1alpha1',
                                'kind': 'Object',
                                'metadata': {'name': 'test-cp-argocd-app',
                                             'namespace': 'platform'},
                                'spec': {'forProvider': {'manifest': {'kind': 'Application',
                                                                      'spec': {'destination': {'namespace': 'default'}}}}}}]}},
 {'name': 'namespaced-vpa',
  'spec': {'compositionPath': 'apis/ctp/composition.yaml',
           'xrdPath': 'apis/ctp/definition.yaml',
           'validate': True,
           'timeoutSeconds': 60,
           'xr': {'apiVersion': 'gcp.platform.upbound.io/v1alpha1',
                  'kind': 'ControlPlane',
                  'metadata': {'name': 'test-cp', 'namespace': 'platform'},
                  'spec': {'parameters': {'id': 'test-cp',
                                          'location': 'us-central1',
                                          'project': 'my-project',
                                          'version': '1.34',
                                          'nodes': {'count': 2,
                                                    'machineType': 'e2-standard-2'},
                                          'providerVerticalPodAutoscaling': {'enabled': 'yes'}}}},
           'assertResources': [{'apiVersion': 'helm.m.crossplane.io/v1beta1',
                                'kind': 'Release',
                                'metadata': {'name': 'test-cp-vpa',
                                             'namespace': 'platform'},
                                'spec': {'forProvider': {'namespace': 'kube-system'}}}]}},
 {'name': 'namespaced-license',
  'spec': {'compositionPath': 'apis/ctp/composition.yaml',
           'xrdPath': 'apis/ctp/definition.yaml',
           'validate': True,
           'timeoutSeconds': 60,
           'xr': {'apiVersion': 'gcp.platform.upbound.io/v1alpha1',
                  'kind': 'ControlPlane',
                  'metadata': {'name': 'test-cp', 'namespace': 'platform'},
                  'spec': {'parameters': {'id': 'test-cp',
                                          'location': 'us-central1',
                                          'project': 'my-project',
                                          'version': '1.34',
                                          'nodes': {'count': 2,
                                                    'machineType': 'e2-standard-2'},
                                          'license': {'secretRef': {'name': 'uxp-license',
                                                                    'namespace': 'default'}}}}},
           'assertResources': [{'apiVersion': 'kubernetes.m.crossplane.io/v1alpha1',
                                'kind': 'Object',
                                'metadata': {'name': 'test-cp-uxp-license-secret',
                                             'namespace': 'platform'},
                                'spec': {'forProvider': {'manifest': {'metadata': {'namespace': 'crossplane-system'}}},
                                         'references': [{'patchesFrom': {'namespace': 'default'}}]}}]}}]
